{% set name = "yamlable" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yamlable-{{ version }}.tar.gz
  sha256: 45feb2150eee63626ed01712883d4cd7c53ff25eda8aaceab3b85e7f710c72a7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.5
    - setuptools >=39.2
    - setuptools-scm
    - wheel
    - pytest-runner
    - pip
  run:
    - python >=3.5
    - pyyaml
    - six

test:
  imports:
    - yamlable
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/smarie/python-yamlable
  summary: A thin wrapper of PyYaml to convert Python objects to YAML and back.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - smarie
